// 业务语义不等于线格式证据；无法确认的名称翻译始终标为推断。
import overrides from "./comment-overrides.json" with { type: "json" };
const words = {
  common: "公共消息信息",
  user: "用户",
  room: "直播间",
  chat: "弹幕",
  emoji: "表情",
  gift: "礼物",
  member: "入场成员",
  like: "点赞",
  social: "关注及社交",
  follow: "关注",
  fans: "粉丝",
  club: "粉丝团",
  link: "连线",
  linker: "连麦",
  linkmic: "连麦",
  mic: "麦位",
  battle: "对战",
  rank: "榜单",
  ranklist: "榜单",
  stats: "统计",
  count: "数量",
  total: "累计总量",
  id: "标识",
  msg: "消息",
  message: "消息",
  content: "内容",
  text: "文本",
  image: "图片",
  avatar: "头像",
  nickname: "昵称",
  nick: "昵称",
  name: "名称",
  url: "资源地址",
  list: "列表",
  info: "信息",
  data: "数据",
  type: "类型",
  status: "状态",
  time: "时间",
  timestamp: "时间戳",
  create: "创建",
  event: "事件",
  send: "发送",
  sender: "发送方",
  receiver: "接收方",
  to: "目标",
  from: "来源",
  repeat: "连击",
  combo: "连击",
  diamond: "钻石",
  coin: "金币",
  price: "价格",
  duration: "持续时间",
  ms: "毫秒",
  second: "秒",
  score: "分数",
  level: "等级",
  priority: "优先级",
  visible: "可见性",
  background: "背景",
  color: "颜色",
  screen: "屏幕",
  public: "公屏",
  area: "区域",
  anchor: "主播",
  audience: "观众",
  display: "展示",
  style: "样式",
  config: "配置",
  setting: "设置",
  settings: "设置",
  version: "版本",
  wrds: "增量同步",
  offset: "消息偏移",
  cursor: "拉取游标",
  heartbeat: "心跳",
  ack: "确认回执",
  need: "是否需要",
  payload: "二进制载荷",
  encoding: "编码方式",
  method: "消息路由方法",
  headers: "传输头列表",
  seq: "传输序号",
  seqid: "传输序号",
  logid: "日志关联标识",
  log: "日志",
  internal: "内部",
  ext: "扩展",
  fetch: "拉取",
  interval: "间隔",
  route: "路由",
  params: "参数",
  push: "推送",
  server: "服务端",
  history: "历史消息",
  now: "服务端当前时间",
  key: "键",
  value: "值",
  request: "请求",
  response: "响应",
  frame: "帧",
  header: "头",
  compress: "压缩",
  zlib: "压缩算法",
  zstd: "压缩算法",
  none: "无",
  enable: "启用",
  disable: "禁用",
  open: "开放",
  close: "关闭",
  start: "开始",
  end: "结束",
  success: "成功",
  fail: "失败",
  unknown: "未知",
  default: "默认",
  true: "是",
  false: "否",
  normal: "正常",
  enter: "进入",
  leave: "离开",
  join: "加入",
  reply: "回复",
  invite: "邀请",
  update: "更新",
  switch: "切换",
  game: "游戏",
  play: "玩法",
  team: "队伍",
  task: "任务",
  banner: "横幅",
  notice: "通知",
  notify: "通知",
  toast: "提示",
  roommessage: "房间通知",
  permission: "权限",
  privilege: "权益",
  title: "标题",
  description: "描述",
  describe: "描述",
  schema: "跳转地址",
  uri: "资源标识",
  extra: "附加",
  map: "映射",
  strategy: "策略",
  tracking: "埋点",
  biz: "业务",
  live: "直播",
  im: "即时消息",
  webcast: "直播协议",
  revenue: "收入",
  reward: "奖励",
  channel: "频道",
  app: "应用",
  aid: "应用标识",
  device: "设备",
  platform: "平台",
  anonymous: "匿名",
  gender: "性别",
  short: "短标识",
  signature: "签名",
  telephone: "电话",
  city: "城市",
  birthday: "生日",
  monitor: "监控",
  control: "控制",
  stream: "音视频流",
  audio: "音频",
  video: "视频",
  record: "记录",
  payment: "支付",
  order: "订单",
  linkmic: "连麦",
  contribution: "贡献",
  auxiliary: "辅助",
  redpacket: "红包",
  lucky: "幸运",
  money: "金额",
  ticket: "票据",
  info: "信息",
  v2: "第二版",
  v3: "第三版",
};
export function translate(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .split(/[_\s.]+/)
    .filter(Boolean)
    .map((x) => words[x.toLowerCase()] || `「${x}」`)
    .join("·");
}
export function scene(full) {
  const s = full.toLowerCase();
  for (const [re, label] of [
    [/chat|emoji/, "弹幕及表情互动"],
    [/gift|diamond|revenue/, "礼物赠送、连击及收益"],
    [/member|enter/, "观众入场及成员变化"],
    [/like/, "点赞互动"],
    [/social|follow|fans/, "关注、粉丝团及社交互动"],
    [/link|battle|mic/, "主播连麦及对战"],
    [/rank|stats/, "直播榜单及统计"],
    [
      /pushframe|response|request|payloadinim|\.message$/,
      "长连接、分页、心跳及 ACK",
    ],
    [/game|team/, "直播游戏及组队玩法"],
  ])
    if (re.test(s)) return label;
  return "直播业务状态、配置及展示";
}
const known = {
  "webcast.im.PushFrame":
    "WebCast 长连接外层帧，携带传输序号、头信息及内层载荷；用于消息、心跳和确认回执",
  "webcast.im.Response": "批量下行响应，包含消息列表、分页游标和确认回执要求",
  "webcast.im.Message":
    "单条消息信封，通过 method 分派业务载荷；msg_type 是信封属性，不是消息定义的唯一编号",
  "webcast.im.ChatMessage": "直播弹幕消息，携带发送用户、文本和公屏展示信息",
  "webcast.im.GiftMessage": "直播礼物消息，携带送礼用户、礼物信息及连击状态",
  "webcast.im.MemberMessage": "直播间成员及入场消息，携带用户和入场展示信息",
  "webcast.im.LikeMessage": "直播点赞消息，携带点赞用户、次数及累计信息",
};
const fields = {
  payload: "本层协议的二进制载荷；信封载荷根据 method 路由至业务解码器",
  method: "传输或消息路由方法；业务信封中的字符串用于匹配官方消息类型",
  content: "弹幕、通知或业务展示内容；具体语义由所属消息决定",
  need_ack: "服务端要求客户端发送 ACK 确认的标记",
  internal_ext: "服务端内部扩展串；确认回执时按原值返回",
  cursor: "服务端下发的拉取游标，用于后续分页或恢复位置",
  heartbeat_duration:
    "服务端心跳间隔提示；单位及零值策略需结合当前 SDK 处理逻辑验证",
  msg_id: "消息标识；64 位值使用十进制字符串输出以避免精度丢失",
  msg_type: "信封携带的消息类别数值；并非全局唯一的消息类型 ID",
  payload_encoding: "载荷编码或压缩声明；同时检查 compress_type 等传输头",
  payload_type: "外层载荷分类，用于区分业务消息、心跳及 ACK",
  SeqID: "外层传输序号；确认帧应关联原始消息序号",
  LogID: "外层日志关联标识；用于确认回执和传输关联",
  headers: "传输头键值列表，可包含压缩类型、内部扩展及游标",
  user: "与当前消息相关的用户资料；送礼、弹幕或入场场景由所属消息决定",
};
export function messageComment(t) {
  return `${known[t.fullName] || `名称推断：${translate(t.fullName.split(".").at(-1))}；用于${scene(t.fullName)}，业务细节待样本确认`}。来源：官方 Parser 运行时定义。`;
}
export function fieldComment(t, f) {
  return `${overrides[t.fullName]?.[f.name] || fields[f.name] || `名称推断：${translate(f.name)}；用于${scene(t.fullName)}，精确业务含义待样本确认`}。结构：${f.keyType ? "键值映射" : f.repeated ? "重复列表" : "单值"}；来源：官方解码字段 ${f.id}。`;
}
export function enumComment(e) {
  return `名称推断：${translate(e.fullName.split(".").at(-1))}枚举；用于${scene(e.fullName)}，取值来自官方运行时，字段关联未提供时不强行替换整数类型。`;
}
export function valueComment(name) {
  return `名称推断：${translate(name)}；枚举数值由官方 Parser 定义，触发条件待样本确认。`;
}
